route:
  receiver: 'pachka-notifier'
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 1m
  repeat_interval: 3h

receivers:
  - name: 'pachka-notifier'
    webhook_configs:
      - url: http://notifier:3002/alert
        send_resolved: true
