global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pachka-services'
    metrics_path: /metrics
    static_configs:
      - targets:
          - gateway:3000
          - router:3001
          - notifier:3002
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [job]
        target_label: service

rule_files:
  - /etc/prometheus/alert.rules.yml
